"""Install-time compiled CUDA kernels for wall_x ops.

Auto-generated by scripts/extract_cuda_kernels.py.
Do not edit manually.
"""

_module = None


def load():
    """Load the CUDA extension module built by setup.py."""
    global _module
    if _module is not None:
        return _module

    try:
        from wall_x.model.core.ops import _cuda_ext_bin
    except ImportError as exc:
        raise ImportError(
            "Wall-X CUDA operators were not built. Install requirements first, "
            "then reinstall Wall-X with: "
            "MAX_JOBS=8 pip install --no-build-isolation -e ."
        ) from exc

    _module = _cuda_ext_bin
    return _module


def is_available() -> bool:
    """Check whether the install-time CUDA extension can be imported."""
    try:
        load()
        return True
    except Exception:
        return False
